bookmarks:
    - path: ~/repos/nikbrunner/dots
    - path: ~/repos/nikbrunner/notes
    - path: ~/repos/nikbrunner/dcd-notes
    - path: ~/repos/nikbrunner/scarth-johnson
    - path: ~/repos/black-atom-industries/core
    - path: ~/repos/black-atom-industries/nvim
    - path: ~/repos/black-atom-industries/radar.nvim
    - path: ~/repos/nikbrunner/nbr.haus
    - path: ~/repos/black-atom-industries/helm
    - path: ~/repos/dealercenter-digital/bc-desktop-client
